# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #        node-version: [16.x, 18.x]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      - run: chrome --version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm run test:ci
        env:
          CHROME_BIN: "chrome"
      - run: npm run e2e:ci
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos/
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
